apiVersion: apps/v1
kind: Deployment
metadata:
  name: lucca-chat-container-deployment
spec:
  replicas: 2
  selector:
      matchLabels:
        app: lucca-chat-container-application
  template:
    metadata:
      labels: # labels to select/identify the deployment
        app: lucca-chat-container-application
    spec:     # pod spec                  
      containers: 
      - name: lucca-chat-container
        image: us.icr.io/luccaspace/lucca-chat-container:latest # image we pushed
        ports:
        - containerPort: 8080